name: Fly Deploy
on:
  push:
    branches:
      - '*'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      environment: python-flask
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
          env:
            DBADDR: ${{ secrets.DBADDR }}
            DBNAME: ${{ secrets.DBNAME }}
            DBPASS: ${{ secrets.DBPASS }}
            DBPORT: ${{ secrets.DBPORT }}
            DBUSER: ${{ secrets.DBUSER }}